# -*- coding: utf-8 -*-
"""Gemma4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QF5AVVygREQYqqs-0jfdkS6ZnKW2e3gE

# 🔥Upgrade transformer for Gemma4 architecture
"""

!pip install -q --upgrade transformers

import json
from transformers import AutoProcessor, AutoModelForCausalLM
from PIL import Image
import librosa
import torchaudio
import torch

"""# 🚀Load model"""

# Inference function
def infer(processor, model, messages):
    inputs = processor.apply_chat_template(
      messages,
      tokenize=True,
      return_dict=True,
      return_tensors="pt",
      add_generation_prompt=True,
    ).to(model.device)

    input_len = inputs["input_ids"].shape[-1]

    outputs = model.generate(**inputs, max_new_tokens=1024)
    response = processor.decode(outputs[0][input_len:], skip_special_tokens=False)

    result = processor.parse_response(response)
    return result

MODEL_ID = "google/gemma-4-E2B-it" # Hugging Face

processor = AutoProcessor.from_pretrained(MODEL_ID)
model = AutoModelForCausalLM.from_pretrained(
    MODEL_ID,
    dtype="auto",
    device_map="cuda:0"
)

"""# 🧪Test Gemma4 Capability

## 💬Chat chit
"""

messages = [
    {
        "role": "system",
        "content": [
            {"type": "text", "text": "You are a helpful assistant."}
        ],
    },
    {
        "role": "user",
        "content": [
            {"type": "text", "text": "Trong truyện Tấm Cám, Tấm và Cám ai là chị? Ai là em?"}
        ],
    },
]

result = infer(processor, model, messages)
print(json.dumps(result,indent=4, ensure_ascii=False))

"""## ✅Intent classification"""

messages = [
    {
        "role": "system",
        "content": [
            {"type": "text", "text": "Bạn là chuyên gia phân loại intent người dùng. Không trả lời mà hãy phân loại câu hỏi người dùng vào các loại: Tiền gửi, Tiền vay và khác."}
        ],
    },
    {
        "role": "user",
        "content": [
            {"type": "text", "text": "Lãi suất tiết kiệm giờ bao nhiêu?"}
        ],
    },
]

result = infer(processor, model, messages)
print(json.dumps(result,indent=4, ensure_ascii=False))

"""## 🌠Describe image"""

from PIL import Image

image_name = "download.jpeg"
image = Image.open(image_name) # Load image
messages = [
    {
        "role": "user",
        "content": [
            {"type": "image", "image": image},
            {"type": "text", "text": "Hãy mô tả địa danh trong hình và đoán xem nó ở quốc gia nào?."}
        ]
    }
]

result = infer(processor, model, messages)
print(json.dumps(result,indent=4, ensure_ascii=False))

from IPython.display import Image, display
display(Image(image_name))

"""## 🔍OCR Document"""

from PIL import Image

image_name = "sample.png"
image = Image.open(image_name) # Load image
messages = [
    {
        "role": "user",
        "content": [
            {"type": "image", "image": image},
            {"type": "text", "text": "Trích xuất thông tin: Người gửi, Người nhận, Số tiền chuyển và Loại tiền (ví dụ VND, USD...). Trả về dạng JSON"}
        ]
    }
]

result = infer(processor, model, messages)
print(json.dumps(result,indent=4, ensure_ascii=False))

from IPython.display import Image, display
display(Image(image_name))

"""## 📈Phân tích hình ảnh, số liệu"""

from PIL import Image

image_name = "chart.png"
image = Image.open(image_name) # Load image
messages = [
    {
        "role": "system",
        "content": [
            {"type": "text", "text": "Bạn là chuyên gia phân tích số liệu"}
        ],
    },
    {
        "role": "user",
        "content": [
            {"type": "image", "image": image},
            {"type": "text", "text": "Phân tích xu hướng của số liệu trong biểu đồ"}
        ]
    }
]
result = infer(processor, model, messages)
print(json.dumps(result,indent=4, ensure_ascii=False))

from IPython.display import Image, display
display(Image(image_name))

"""## ⓶Multi Input Images"""

from PIL import Image

image_name = "people.png"
image_name_1 = "sample.png"

image1 = Image.open(image_name)
image2 = Image.open(image_name_1)
messages = [
    {
        "role": "system",
        "content": [
            {"type": "text", "text": "Bạn là chuyên gia phân tích hình ảnh"}
        ],
    },
    {
        "role": "user",
        "content": [
            {"type": "image", "image": image1},
            {"type": "image", "image": image2},
            {"type": "text", "text": "Bạn nhìn có khuôn mặt người trong hình không?"}
        ]
    }
]
result = infer(processor, model, messages)
print(json.dumps(result,indent=4, ensure_ascii=False))

from IPython.display import Image, display
display(Image(image_name))

"""## 💻Coding"""

messages = [{
        "role": "system",
        "content": [
            {"type": "text", "text": "You are a coder. Only return source code, nothing else"}
        ],
    },
    {
        "role": "user",
        "content": [
            {
                "type": "text",
                "text": "Write a python script to save a file from https://miai.vn/wp-content/uploads/2026/05/cropped-Logo_w_slogan.png to C drive"
            }
        ],
    }
]

infer(processor, model, messages)

"""## Speech to Text"""

def load_audio(audio_path: str, target_sr: int = 16000):

    waveform, sample_rate = torchaudio.load(audio_path)

    # Convert stereo → mono nếu cần
    if waveform.shape[0] > 1:
        waveform = waveform.mean(dim=0, keepdim=True)

    # Resample về target_sr
    if sample_rate != target_sr:
        resampler = torchaudio.transforms.Resample(
            orig_freq=sample_rate,
            new_freq=target_sr
        )
        waveform = resampler(waveform)

    # Trả về numpy array 1D
    audio_array = waveform.squeeze().numpy()
    print(f"✅ Loaded audio: {audio_path}")
    print(f"   Duration: {len(audio_array) / target_sr:.2f}s | Sample rate: {target_sr}Hz")
    return audio_array, target_sr

audio_array,_ = load_audio("record.mp3")

from IPython.display import Audio, display
sound_file = 'record.mp3'
display(Audio(sound_file, autoplay=True))

language = "Vietnamese"
messages = [
        {
            "role": "user",
            "content": [
                {
                    "type": "audio",
                    "audio": audio_array,
                },
                {
                    "type": "text",
                    "text": f"Please transcribe this {language} audio exactly as spoken. Output only the transcription text, nothing else."
                }
            ]
        }
    ]
infer(processor, model, messages)

"""## Ollam host"""

import base64
import requests
import json

def ocr_with_ollama(image_path, model = "gemma4:e4b"):
    # Đọc ảnh
    with open(image_path, "rb") as image_file:
        image_data = base64.b64encode(image_file.read()).decode("utf-8")

    prompt = "Hãy đọc và trích xuất thông tin từ văn bản: Người chuyển, Người nhận, Số tiền chuyển và loại tiền (ví dụ USD, VND...). Trả về dạng JSON."

    payload = {
        "model": model,
        "prompt": prompt,
        "images": [image_data],
        "stream": False
    }

    response = requests.post(
        "https://ord986546-11434.pod.vaza.vn/api/generate",
        json=payload
    )
    response.raise_for_status()
    return response.json()["response"]


if __name__ == "__main__":
    result = ocr_with_ollama("sample.png")
    print(result)